### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by OpvpYT** [lucko/BungeeGuard#12]
```
[02:36:09 ERROR]: [Ashrame|/92.157.11.159:62546] <-> ServerConnector [faction] - encountered exception
io.netty.handler.codec.CorruptedFrameException: Empty Packet!
at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:45) ~[server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259]
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433) ~[server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330) ~[server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:dceeeb3:259]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by lucko** [comment]
Not a BungeeGuard error
