### ISSUE TITLE
weird glitch (i dont understand it)

### ISSUE THREAD

**Issue by c0d3rb0y** [lucko/BungeeGuard#37]
Well, it won't generate any token file. Or load.
Error:

Could not load plugin from file plugins/BungeeGuard.jar
java.util.zip.ZipException: zip END header not found
    at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1535)
    at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1436)
    at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1443)
    at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274)
    at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
    at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
    at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
    at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
    at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
    at java.base/java.util.jar.JarFile.<init>(JarFile.java:348)
    at java.base/java.util.jar.JarFile.<init>(JarFile.java:319)
    at java.base/java.util.jar.JarFile.<init>(JarFile.java:285)
    at net.md_5.bungee.api.plugin.PluginManager.detectPlugins(PluginManager.java:360)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:270)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

edit: i am trying this in 1.16 tho, so compatibility is probably about 😐 on scale of 😄 to 😢  (mid)
Spigot server part works. Bungee doesn't.

**Comment by stijnb1234** [comment]
Where did you download the bungeecord jar?

**Comment by c0d3rb0y** [comment]
spigotmc website, why?

**Comment by stijnb1234** [comment]
https://github.com/lucko/BungeeGuard/releases/tag/v1.2.0

Try this one.

**Comment by c0d3rb0y** [comment]
worked perfect! thx!
