### ISSUE TITLE
Error thrown while trying to load plugin

### ISSUE THREAD

**Issue by CyberFlameGO** [lucko/BungeeGuard#47]
```java
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/lucko/bungeeguard/spigot/BungeeGuardBackendPlugin has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[a.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:335) ~[a.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:252) [a.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [a.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:207) [a.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:568) [a.jar:git-TacoSpigot-bf023c7d]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.UnsupportedClassVersionError: me/lucko/bungeeguard/spigot/BungeeGuardBackendPlugin has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by stijnb1234** [comment]
Update to Java 9 or higher.

**Comment by CyberFlameGO** [comment]
Okay, thank you!
