### ISSUE TITLE
Error dispatching event LoginEvent console error spam

### ISSUE THREAD

**Issue by benfiratkaya** [lucko/BungeeGuard#61]
What's mean this error? It's only coming when we under attack.

```
[00:14:25] [pool-6-thread-119/WARN]: Error dispatching event LoginEvent(cancelled=false, cancelReasonComponents=null, loginResult=null, connection=[/ipaddress:56334|1] <-> InitialHandler) to listener me.lucko.bungeeguard.bungee.BungeeGuardProxyPlugin@1328f482
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at me.lucko.bungeeguard.bungee.SpoofedLoginResult.inject(SpoofedLoginResult.java:83) ~[?:?]
	at me.lucko.bungeeguard.bungee.BungeeGuardProxyPlugin.onLogin(BungeeGuardProxyPlugin.java:110) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[proxy.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:ca8c6ed:unknown]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:48) ~[proxy.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:ca8c6ed:unknown]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:510) ~[proxy.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:ca8c6ed:unknown]
	at net.md_5.bungee.connection.InitialHandler.finish(InitialHandler.java:621) ~[proxy.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:ca8c6ed:unknown]
	at net.md_5.bungee.connection.InitialHandler.access$800(InitialHandler.java:74) ~[proxy.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:ca8c6ed:unknown]
	at net.md_5.bungee.connection.InitialHandler$4.done(InitialHandler.java:452) ~[proxy.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:ca8c6ed:unknown]
	at net.md_5.bungee.connection.InitialHandler$4.done(InitialHandler.java:431) ~[proxy.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:ca8c6ed:unknown]
	at net.md_5.bungee.api.event.AsyncEvent.completeIntent(AsyncEvent.java:87) ~[proxy.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:ca8c6ed:unknown]
	at de.antibotdeluxe.blackhole.proxy.listener.PreLoginListener.lambda$onPreLogin$0(PreLoginListener.java:39) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_292]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor96.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_292]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_292]
	at me.lucko.bungeeguard.bungee.SpoofedLoginResult.inject(SpoofedLoginResult.java:80) ~[?:?]
	... 18 more
Caused by: java.lang.RuntimeException: getId called for offline variant of SpoofedLoginResult
	at me.lucko.bungeeguard.bungee.SpoofedLoginResult.getId(SpoofedLoginResult.java:126) ~[?:?]
	at me.lucko.bungeeguard.bungee.SpoofedLoginResultJava8.getId(SpoofedLoginResultJava8.java:30) ~[?:?]
	at me.lucko.bungeeguard.bungee.SpoofedLoginResult.<init>(SpoofedLoginResult.java:99) ~[?:?]
	at me.lucko.bungeeguard.bungee.SpoofedLoginResultJava8.<init>(SpoofedLoginResultJava8.java:36) ~[?:?]
	at sun.reflect.GeneratedConstructorAccessor96.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_292]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_292]
	at me.lucko.bungeeguard.bungee.SpoofedLoginResult.inject(SpoofedLoginResult.java:80) ~[?:?]
	... 18 more
```

**Comment by J0ddy** [comment]
I have the same error. It would be nice to find out where it's coming from.

**Comment by AdamFalconieri** [comment]
Still have this error as of today. I properly configured BungeeGuard in both Bungee & all spigot servers (with ProtocolLib installed!), but BungeeGuard is flooding all spigots' consoles with this exact error. Any fix? Where is it coming from? Is the system working even with this console error?

Specs:
- Latest bungeecord version (as of April, 2026)
- Back-end is running 1.21.11 spigot
