### ISSUE TITLE
Dont't work whit skins restorer

### ISSUE THREAD

**Issue by MineCityZolii** [lucko/BungeeGuard#7]
Hi! This plugin is not working if you put the SkinsRestorer (Link: https://www.spigotmc.org/resources/skinsrestorer.2124/ ) Cloud you fix it?

**Comment by lucko** [comment]
I don't have much time to look into this at the moment. Would happily accept a PR fixing it.

**Comment by CallMeGhosty** [comment]
Hello, could you look now into the issue?

**Comment by lucko** [comment]
I suspect the problematic code is here:
https://github.com/SkinsRestorer/SkinsRestorerX/blob/8b3efd5aaa9390ba1e55ca64a77c6d0e64c1168e/src/main/java/skinsrestorer/bungee/SkinApplier.java#L46-L68

Which conflicts with:
https://github.com/lucko/BungeeGuard/blob/master/bungeeguard-proxy/src/main/java/me/lucko/bungeeguard/proxy/SpoofedLoginResult.java

This is something the SkinsRestorer author would need to fix.

**Comment by lucko** [comment]
@DoNotSpamPls would you be able to look into this?

This code in particular doesn't seem very sane to me.

https://github.com/SkinsRestorer/SkinsRestorerX/blob/8b3efd5aaa9390ba1e55ca64a77c6d0e64c1168e/src/main/java/skinsrestorer/bungee/SkinApplier.java#L46-L68

Creating a totally new `LoginResult` seems redundant - could SkinsRestorer not just modify the properties inside of the existing object?

The manipulation of the Property arrays also seems odd - I can't really follow what that code is even meant to be doing?

**Comment by DoNotSpamPls** [comment]
Hi @lucko, unfortunately I don't develop SkinsRestorer anymore, so I can't help much. However, I'm pinging @McLive here and in DMs, he may be able to assist you.

**Comment by McLive** [comment]
@lucko Somehow I can't access the LoginResult provided by BungeeGuard...

`            Property[] present = profile.getProperties();
            System.out.println("present props:");
            System.out.println(present.toString());
            for (Property prop : present) {
                System.out.println(prop.getName());
            }
            System.out.println(present[0]);`

> 17:52:00 [INFORMATION] present props:
17:52:00 [INFORMATION] [Lnet.md_5.bungee.connection.LoginResult$Property;@654a3041
17:52:00 [SCHWERWIEGEND] java.lang.ArrayIndexOutOfBoundsException: 0
17:52:00 [SCHWERWIEGEND]     at skinsrestorer.bungee.SkinApplier.applySkin(SkinApplier.java:64)
17:52:00 [SCHWERWIEGEND]     at skinsrestorer.bungee.listeners.LoginListener$1.run(LoginListener.java:82)
17:52:00 [SCHWERWIEGEND]     at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
17:52:00 [SCHWERWIEGEND]     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
17:52:00 [SCHWERWIEGEND]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
17:52:00 [SCHWERWIEGEND]     at java.lang.Thread.run(Unknown Source)

Did I missed something?

**Comment by McLive** [comment]
@MineCityZolii @CallMeGhosty Could you please try if the [recent version](https://ci.freecraft.eu/v2/job/SkinsRestorerX/11/) fixes this issue? Thank you!

**Comment by CallMeGhosty** [comment]
Yes, it works! Thanks for the fast response. I think this issue can be closed now.
Thank you @lucko and @McLive!
