### ISSUE TITLE
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by Skizzles** [lucko/BungeeGuard#73]
<-> InitialHandler) to listener me.lucko.bungeeguard.bungee.BungeeGuardProxyPlugin@2d94467b
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at me.lucko.bungeeguard.bungee.SpoofedLoginResult.inject(SpoofedLoginResult.java:83) ~[?:?]
        at me.lucko.bungeeguard.bungee.BungeeGuardProxyPlugin.onLogin(BungeeGuardProxyPlugin.java:110) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor40.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at net.md_5.bungee.connection.InitialHandler.finish(InitialHandler.java:599) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at net.md_5.bungee.connection.InitialHandler.access$800(InitialHandler.java:76) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at net.md_5.bungee.connection.InitialHandler$5.done(InitialHandler.java:494) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at net.md_5.bungee.connection.InitialHandler$5.done(InitialHandler.java:482) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at net.md_5.bungee.http.HttpHandler.done(HttpHandler.java:68) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at net.md_5.bungee.http.HttpHandler.channelRead0(HttpHandler.java:59) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at net.md_5.bungee.http.HttpHandler.channelRead0(HttpHandler.java:14) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.19-490.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:0e38b9b:490]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.GeneratedConstructorAccessor60.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at me.lucko.bungeeguard.bungee.SpoofedLoginResult.inject(SpoofedLoginResult.java:80) ~[?:?]
        ... 48 more
Caused by: java.lang.NoSuchMethodError: 'net.md_5.bungee.connection.LoginResult$Property[] net.md_5.bungee.connection.LoginResult.getProperties()'
        at me.lucko.bungeeguard.bungee.SpoofedLoginResult.<init>(SpoofedLoginResult.java:99) ~[?:?]
        at me.lucko.bungeeguard.bungee.SpoofedLoginResultJava9.<init>(SpoofedLoginResultJava9.java:36) ~[?:?]
        at jdk.internal.reflect.GeneratedConstructorAccessor60.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at me.lucko.bungeeguard.bungee.SpoofedLoginResult.inject(SpoofedLoginResult.java:80) ~[?:?]
        ... 48 more

**Comment by stijnb1234** [comment]
Duplicate of #74
