### ISSUE TITLE
Bungee (Waterfall) | 1.19 Server Error

### ISSUE THREAD

**Issue by Hax100** [lucko/BungeeGuard#78]
Hi, I am having issues with getting bungeeguard working.
I am going from 1.18.2 lobby server to 1.19 survival server
We obviously have via versions installed in the bungee. 
at first, I thought it was a ProtocolLib issue but their support team says its a bungeeguard issue 

"This seems to be an issue with BungeeGuard trying to access a class which no longer exists (com.comphenix.protocol.injector.server.TemporaryPlayerFactory). Please report it to them" - derklaro
Read my issue post in ProtocolLib: https://github.com/dmulloy2/ProtocolLib/issues/1619

Please help :(.

**Comment by Hax100** [comment]
**Additional Error Context:**
me doing "/server UpdatedSurvival" results in this error `[11.06 22:22:40] [Disconnect] /xxx.xx.xx.has disconnected, reason: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(8) + length(1) exceeds writerIndex(8): PooledUnsafeDirectByteBuf(ridx: 8, widx: 8, cap: 8)`

and when i attempt a direct ip connection it results in this error: {obviously we want it to block people from connecting via the direct IP and use the bungee IP so its good it blocks me but it still does give a bigggg error}
```
[11.06 22:24:15] [Server] [Netty Epoll Server IO #1/WARN]: [BungeeGuard] Denying connection from xxx.xx.xx.xxx - XXXXXXXXXXXXXXXXX== - reason: INVALID_HANDSHAKE
[11.06 22:24:15] [Server] 2022-06-19:24:15,711 Netty Epoll Server IO #1 ERROR Recursive call to appender File
[11.06 22:24:15] [Server] [Netty Epoll Server IO #1/WARN]: [ProtocolLib] Loaded class me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener$Adapter from BungeeGuard v1.3-SNAPSHOT which is not a depend or softdepend of this plugin.
[11.06 22:24:15] [Server] [Netty Epoll Server IO #1/ERROR]: [BungeeGuard] Unhandled exception occurred in onPacketReceiving(PacketEvent) for BungeeGuard
[11.06 22:24:15] [Server] java.lang.NoClassDefFoundErrorcom/comphenix/protocol/injector/server/TemporaryPlayerFactory
[11.06 22:24:15] [Server] 	at me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener.closeConnection(ProtocolHandshakeListener.java:130) ~[BungeeGuard.jar:?]
[11.06 22:24:15] [Server] 	at me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener.access$300(ProtocolHandshakeListener.java:54) ~[BungeeGuard.jar:?]
[11.06 22:24:15] [Server] 	at me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener$Adapter.onPacketReceiving(ProtocolHandshakeListener.java:103) ~[BungeeGuard.jar:?]
[11.06 22:24:15] [Server] 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:5.0.0-SNAPSHOT-b567]
[11.06 22:24:15] [Server] 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:5.0.0-SNAPSHOT-b567]
[11.06 22:24:15] [Server] 	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:554) [ProtocolLib.jar:5.0.0-SNAPSHOT-b567]
[11.06 22:24:15] [Server] 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketReceiving(PacketFilterManager.java:519) [ProtocolLib.jar:5.0.0-SNAPSHOT-b567]
[11.06 22:24:15] [Server] 	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketReceiving(NetworkManagerInjector.java:113) [ProtocolLib.jar:5.0.0-SNAPSHOT-b567]
[11.06 22:24:15] [Server] 	at com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:31) [ProtocolLib.jar:5.0.0-SNAPSHOT-b567]
[11.06 22:24:15] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:90) [spigot-1.19-R0.1-SNAPSHOT.jar:3523-Spigot-1dffefb-effea36]
[11.06 22:24:15] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) [netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) [netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:4.1.77.Final]
[11.06 22:24:15] [Server] 	at java.lang.Thread.run(Thread.java:833) [?:?]
[11.06 22:24:15] [Server] Caused byjava.lang.ClassNotFoundException: com.comphenix.protocol.injector.server.TemporaryPlayerFactory
[11.06 22:24:15] [Server] 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
[11.06 22:24:15] [Server] 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
[11.06 22:24:15] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[11.06 22:24:15] [Server] 	... more
[11.06 22:24:15] [Server] [Netty Epoll Server IO #1/ERROR]: Parameters: 
[11.06 22:24:15] [Server]   net.minecraft.network.protocol.handshake.PacketHandshakingInSetProtocol@5198772b[
[11.06 22:24:15] [Server]     b=759
[11.06 22:24:15] [Server]     c=xxx.xxx.xx.xx
[11.06 22:24:15] [Server]     d=25565
[11.06 22:24:15] [Server]     e=LOGIN
[11.06 22:24:15] [Server]   ]
[11.06 22:24:15] [Disconnect] /xxx.xx.xx.has disconnected, reason: If you wish to use IP forwarding, please enable it in your BungeeCord config as well!
```

**Comment by lucko** [comment]
Should be resolved - thanks

**Comment by Hax100** [comment]
ok I updated to the version you just released : still erroring 
```
[12.06 11:03:12] [Disconnect] /xxx.xxx.xxx.has disconnected, reason: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(8) + length(1) exceeds writerIndex(8): PooledUnsafeDirectByteBuf(ridx: 8, widx: 8, cap: 8)
[12.06 11:03:20] [Server] [Netty Epoll Server IO #0/WARN]: [BungeeGuard] Denying connection from xxx.xxx.xxx.xxx - xxxxxxxxxxxxxxxxxxxx== - reason: INVALID_HANDSHAKE
```
Do you know anything about the Disconnect error?
And
The "allowed-tokens:" from configs does match across all servers so idk why it thinks it's invalid
