### ISSUE TITLE
 Error dispatching event LoginEvent

### ISSUE THREAD

**Issue by thevalleyy** [lucko/BungeeGuard#81]
This error occurs on my proxy, I removed some values due to privacy:

```
[10:28:25 WARN]: Error dispatching event LoginEvent(cancelled=false, cancelReasonComponents=null, loginResult=LoginResult(id=162709bf8ed24f5880c8e524b659eeec, name=thevalleyy, properties=[LoginResult.Property(<removed value>), connection=[<removed value>] <-> InitialHandler) to listener me.lucko.bungeeguard.bungee.BungeeGuardProxyPlugin@4fc6e776
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at me.lucko.bungeeguard.bungee.SpoofedLoginResult.inject(SpoofedLoginResult.java:82) ~[?:?]
        at me.lucko.bungeeguard.bungee.BungeeGuardProxyPlugin.onLogin(BungeeGuardProxyPlugin.java:111) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at net.md_5.bungee.connection.InitialHandler.finish(InitialHandler.java:573) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at net.md_5.bungee.connection.InitialHandler.access$800(InitialHandler.java:74) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at net.md_5.bungee.connection.InitialHandler$5.done(InitialHandler.java:468) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at net.md_5.bungee.connection.InitialHandler$5.done(InitialHandler.java:456) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at net.md_5.bungee.http.HttpHandler.done(HttpHandler.java:68) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at net.md_5.bungee.http.HttpHandler.channelRead0(HttpHandler.java:59) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at net.md_5.bungee.http.HttpHandler.channelRead0(HttpHandler.java:14) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1371) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.18-486.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:d79d5f1:486]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at me.lucko.bungeeguard.bungee.SpoofedLoginResult.inject(SpoofedLoginResult.java:79) ~[?:?]
        ... 49 more
Caused by: java.lang.NoSuchMethodError: 'net.md_5.bungee.protocol.Property[] net.md_5.bungee.connection.LoginResult.getProperties()'
        at me.lucko.bungeeguard.bungee.SpoofedLoginResult.<init>(SpoofedLoginResult.java:98) ~[?:?]
        at me.lucko.bungeeguard.bungee.SpoofedLoginResultJava9.<init>(SpoofedLoginResultJava9.java:36) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at me.lucko.bungeeguard.bungee.SpoofedLoginResult.inject(SpoofedLoginResult.java:79) ~[?:?]
        ... 49 more
```

**Comment by thevalleyy** [comment]
oh... after some searching i found out that i can't use the latest version of the plugin. Am I just blind, or is this really only in the releases tab on github? I only found this out by accident, I was about to give up....

**Comment by thevalleyy** [comment]
no, actually the issue is created by the newest release, I'm using waterfall 1.18.2

**Comment by stijnb1234** [comment]
> no, actually the issue is created by the newest release, I'm using waterfall 1.18.2

Update your waterfall then. There is no reason not to, because waterfall 1.19 does also support 1.18.2.
