### ISSUE TITLE
Denying connection from No getting my IP - Or  @ This - reason: NO_TOKEN

### ISSUE THREAD

**Issue by ssl42** [lucko/BungeeGuard#82]
I made sure the token is the same across all the .yml files yet this still happens

**Comment by ssl42** [comment]
[09:24:58] [Netty Epoll Server IO #0/WARN]: [ProtocolLib] Loaded class me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener$Adapter from BungeeGuard v1.2-SNAPSHOT which is not a depend or softdepend of this plugin.
[09:24:58] [Netty Epoll Server IO #0/ERROR]: [BungeeGuard] Unhandled exception occurred in onPacketReceiving(PacketEvent) for BungeeGuard
java.lang.NoClassDefFoundError: com/comphenix/protocol/injector/server/TemporaryPlayerFactory
        at me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener.closeConnection(ProtocolHandshakeListener.java:127) ~[BungeeGuard.jar:?]
        at me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener.access$000(ProtocolHandshakeListener.java:53) ~[BungeeGuard.jar:?]
        at me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener$Adapter.onPacketReceiving(ProtocolHandshakeListener.java:100) ~[BungeeGuard.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:5.0.0-SNAPSHOT-b556]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:5.0.0-SNAPSHOT-b556]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:554) [ProtocolLib.jar:5.0.0-SNAPSHOT-b556]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketReceiving(PacketFilterManager.java:519) [ProtocolLib.jar:5.0.0-SNAPSHOT-b556]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketReceiving(NetworkManagerInjector.java:113) [ProtocolLib.jar:5.0.0-SNAPSHOT-b556]
        at com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:31) [ProtocolLib.jar:5.0.0-SNAPSHOT-b556]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:90) [spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:4.1.68.Final]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.injector.server.TemporaryPlayerFactory
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 42 more
[09:24:58] [Netty Epoll Server IO #0/ERROR]: Parameters: 
  net.minecraft.network.protocol.handshake.PacketHandshakingInSetProtocol@bf0bf1c[
    b=759
    c=a2craft.xyz5.28.133.141c4d76634ce8540d3b7f71df6c38b6fd7[{"name":"textures","value":"ewogICJ0aW1lc3RhbXAiIDogMTY1NTE5NTA5ODM4MiwKICAicHJvZmlsZUlkIiA6ICJjNGQ3NjYzNGNlODU0MGQzYjdmNzFkZjZjMzhiNmZkNyIsCiAgInByb2ZpbGVOYW1lIiA6ICJzc2w0MjIiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2U4NmM5MDNhMTczOWY5ODZiNDRkNGM2MDdmMTQwMzMxNzVlMjk1Y2U4YzIzZmU2NjgwNjI0ZWIwZjY4NzNiNiIKICAgIH0sCiAgICAiQ0FQRSIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjM0MGMwZTAzZGQyNGExMWIxNWE4YjMzYzJhN2U5ZTMyYWJiMjA1MWIyNDgxZDBiYTdkZWZkNjM1Y2E3YTkzMyIKICAgIH0KICB9Cn0\u003d","signature":"VJK8InaSHkNK8jLez/goGUUDwsrOW++QZPbH7t5fsz1E/IlJHyhmI4WRtEFca36PklnrdGsKntr4zlWqVMhKad8K+t7qU9I1CoT/G4kHNxeRYeWedrSwT0jhwxWlcxhKR93URFCXq7brVCoCUAMLwX0JCRuFxC+T/regTxoFabXDcOEQuB5GnugYwKdlcyT96BtAQtKTxq3freLbSz6WJlqXjUFJWumf4tg5FQtvzcw6p+NoPJ2NsW0Sq5Zi8hwYsAVvyqdDmqN2XoY27l9eBbbSnpecevv2yIyQwYLQ1zRClWonvme6VO0TDoTifsMlywu0IBEnWOAXRD772Apf3Kw30FfaIO2Yln9G74U/0nwUahZPpwjLlt1YQIyrMyXpIwJRij6S4GuTUdzGYC/E2byKsphcZzSXCKJT68V4y0drbVyMlO4Y1Jy2iQek0X3G0GvEmV3x4yOkR2GMYQm7xJwOdsjnNp42qRUxAhG3gPoVYbZHWoO3Z6nLSIOqcg9IyvwflmTYFclr9bXVfMtO0xO9y95JkxqwR3IFAgAzshz3Gf5ITRsWutMUQ0vqcPu6hRz/6mxZFgKOqJcdtNIUuE18UUJNwz/ClI0OJMFq58SSqtp3Qecz9t9uRtY0YIqwXTm2U1Btd+JKZexwauT0np9+oNt8ARP+xgb5JyZ9TRA\u003d"}]
    d=30008
    e=LOGIN
  ]
