### ISSUE TITLE
Error in new update

### ISSUE THREAD

**Issue by KaspianDev** [lucko/BungeeGuard#83]
```
[13.06 21:19:52] [Server] [WARNING] A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@6005c8a
[13.06 21:19:52] [Server] java.lang.NoClassDefFoundErrorjdk/internal/reflect/Reflection
[13.06 21:19:52] [Server]     at me.lucko.bungeeguard.bungee.SpoofedLoginResultJava8.getProperties(SpoofedLoginResultJava8.java:47)
[13.06 21:19:52] [Server]     at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:553)
[13.06 21:19:52] [Server]     at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[13.06 21:19:52] [Server]     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[13.06 21:19:52] [Server]     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[13.06 21:19:52] [Server]     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
[13.06 21:19:52] [Server]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[13.06 21:19:52] [Server]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[13.06 21:19:52] [Server]     at java.lang.Thread.run(Thread.java:748)
[13.06 21:19:52] [Server] Caused byjava.lang.ClassNotFoundException: jdk.internal.reflect.Reflection
[13.06 21:19:52] [Server]     at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
[13.06 21:19:52] [Server]     at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
[13.06 21:19:52] [Server]     at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[13.06 21:19:52] [Server]     ... more
[13.06 21:19:53] [Server] [WARNING] A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@320ee692
[13.06 21:19:53] [Server] java.lang.NoClassDefFoundErrorjdk/internal/reflect/Reflection
[13.06 21:19:53] [Server]     at me.lucko.bungeeguard.bungee.SpoofedLoginResultJava8.getProperties(SpoofedLoginResultJava8.java:47)
[13.06 21:19:53] [Server]     at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:553)
[13.06 21:19:53] [Server]     at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[13.06 21:19:53] [Server]     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[13.06 21:19:53] [Server]     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[13.06 21:19:53] [Server]     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
[13.06 21:19:53] [Server]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[13.06 21:19:53] [Server]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[13.06 21:19:53] [Server]     at java.lang.Thread.run(Thread.java:748)
```

**Comment by CemaICT** [comment]
I am getting the same error. No exact clue why though. I see a java8 being referenced. But I am no developer of java.

**Comment by CemaICT** [comment]
Update to the latest Java17 has fixed our issues
