### ISSUE TITLE
An error occurs with the latest version of BungeeCord

### ISSUE THREAD

**Issue by sergservis** [lucko/BungeeGuard#85]
19:18:44 [WARNING] A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@7712c2c1
java.lang.NoClassDefFoundError: jdk/internal/reflect/Reflection
    at me.lucko.bungeeguard.bungee.SpoofedLoginResultJava8.getProperties(SpoofedLoginResultJava8.java:47)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:553)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: jdk.internal.reflect.Reflection
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 9 more

**Comment by sergservis** [comment]
And at this point it appears on the side of Spigot 1.8

[19:20:30 WARN]: Error dispatching event LoginEvent(cancelled=false, cancelReasonComponents=null, loginResult=null, connection=[/127.0.0.1:59046|Flephh] <-> InitialHandler) to listener me.lucko.bungeeguard.bungee.BungeeGuardProxyPlugin@5854a18
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at me.lucko.bungeeguard.bungee.SpoofedLoginResult.inject(SpoofedLoginResult.java:82) ~[?:?]
        at me.lucko.bungeeguard.bungee.BungeeGuardProxyPlugin.onLogin(BungeeGuardProxyPlugin.java:111) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_333]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_333]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_333]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_333]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:510) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at net.md_5.bungee.connection.InitialHandler.finish(InitialHandler.java:762) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at net.md_5.bungee.connection.InitialHandler.access$900(InitialHandler.java:83) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at net.md_5.bungee.connection.InitialHandler$4.done(InitialHandler.java:597) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at net.md_5.bungee.connection.InitialHandler$4.done(InitialHandler.java:576) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at net.md_5.bungee.api.event.AsyncEvent.postCall(AsyncEvent.java:41) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:511) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:603) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at net.md_5.bungee.protocol.packet.LoginRequest.handle(LoginRequest.java:36) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:131) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:514) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:8a78b2b:unknown]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_333]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_333]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_333]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_333]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_333]
        at me.lucko.bungeeguard.bungee.SpoofedLoginResult.inject(SpoofedLoginResult.java:77) ~[?:?]
        ... 52 more
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/protocol/Property
        at me.lucko.bungeeguard.bungee.SpoofedLoginResult.<init>(SpoofedLoginResult.java:106) ~[?:?]
        at me.lucko.bungeeguard.bungee.SpoofedLoginResultJava8.<init>(SpoofedLoginResultJava8.java:42) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_333]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_333]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_333]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_333]
        at me.lucko.bungeeguard.bungee.SpoofedLoginResult.inject(SpoofedLoginResult.java:77) ~[?:?]
        ... 52 more

**Comment by stijnb1234** [comment]
Duplicate of #83
