### ISSUE TITLE
Error in console when joining proxy server

### ISSUE THREAD

**Issue by Vehzx** [lucko/BungeeGuard#86]
When trying to join the proxy all players are stuck on Encrypting and this error is pasted into the proxy console.

A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@796340a4
java.lang.NoClassDefFoundError: jdk/internal/reflect/Reflection
    at me.lucko.bungeeguard.bungee.SpoofedLoginResultJava8.getProperties(SpoofedLoginResultJava8.java:47)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:553)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.lang.Thread.run(Thread.java:748)

**Comment by stijnb1234** [comment]
Duplicate of #83
