### ISSUE TITLE
Error while trying to connect on the server

### ISSUE THREAD

**Issue by AnythingMayBe** [lucko/BungeeGuard#88]
Hello,

After logging in on the proxy, my lobby server gets this error : 

```
[09:42:08 WARN]: [BungeeGuard] Denying connection from 127.0.0.1 - 881ab704-8266-391d-a1f5-51b3aadf3b03 @ MTI3LjAuMC4x - reason: NO_TOKEN
[09:42:08 ERROR]: [BungeeGuard] Unhandled exception occured in onPacketReceiving(PacketEvent) for BungeeGuard
java.lang.NoClassDefFoundError: com/comphenix/protocol/injector/temporary/TemporaryPlayerFactory
	at me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener.closeConnection(ProtocolHandshakeListener.java:134) ~[BungeeGuard.jar:?]
	at me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener.access$300(ProtocolHandshakeListener.java:55) ~[BungeeGuard.jar:?]
	at me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener$Adapter.onPacketReceiving(ProtocolHandshakeListener.java:104) ~[BungeeGuard.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.8.0]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.8.0]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) [ProtocolLib.jar:4.8.0]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) [ProtocolLib.jar:4.8.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) [ProtocolLib.jar:4.8.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) [ProtocolLib.jar:4.8.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:600) [ProtocolLib.jar:4.8.0]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292) [ProtocolLib.jar:4.8.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at net.minecraft.server.v1_8_R3.LegacyPingHandler.channelRead(SourceFile:94) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [goatspigot-1.8.8-R0.1-SNAPSHOT.jar:1.8.8-R0.1-SNAPSHOT]
	at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.injector.temporary.TemporaryPlayerFactory
	... 34 more
[09:42:08 ERROR]: Parameters: 
  net.minecraft.server.v1_8_R3.PacketHandshakingInSetProtocol@3308514d[
    a=47
    hostname=localhost127.0.0.1881ab7048266391da1f551b3aadf3b03
    port=25565
    d=LOGIN
  ]

``` 

The fork used can be found on the Karhu Anticheat Discord server (https://discord.gg/cMY4xKRrW4).
I'm using the latest version of BungeeGuard and ProtocolLib.

**Comment by D0WZ3** [comment]
same errors for my 1.8.8 servers, hope it get fix quick!
