### ISSUE TITLE
Unable to connect to the server 

### ISSUE THREAD

**Issue by PoudreMODInc** [lucko/BungeeGuard#89]
Hello, for a few days now, when I try to connect to my network I got this error everytimes.

[16:18:54 WARN]: [BungeeGuard] Denying connection from ********** - 28e871b6-343e-4024-b710-7c5191ff85b5 @ ODUuMTY5LjI0OS4xMzQ= - reason: NO_TOKEN
[16:18:54 ERROR]: [BungeeGuard] Unhandled exception occured in onPacketReceiving(PacketEvent) for BungeeGuard
java.lang.NoClassDefFoundError: com/comphenix/protocol/injector/temporary/TemporaryPlayerFactory
        at me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener.closeConnection(ProtocolHandshakeListener.java:134) ~[BungeeGuard.jar:?]
        at me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener.access$300(ProtocolHandshakeListener.java:55) ~[BungeeGuard.jar:?]
        at me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener$Adapter.onPacketReceiving(ProtocolHandshakeListener.java:104) ~[BungeeGuard.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.8.0]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.8.0]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) [ProtocolLib.jar:4.8.0]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) [ProtocolLib.jar:4.8.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) [ProtocolLib.jar:4.8.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) [ProtocolLib.jar:4.8.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:600) [ProtocolLib.jar:4.8.0]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [server.jar:git-Spigot-79a30d7-f4830a1]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292) [ProtocolLib.jar:4.8.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [server.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [server.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.injector.temporary.TemporaryPlayerFactory
        ... 40 more
[16:18:54 ERROR]: Parameters: 
  net.minecraft.server.v1_12_R1.PacketHandshakingInSetProtocol@31c58465[
    a=340
    hostname=game7.falixserver.net85.169.249.13428e871b6343e4024b7107c5191ff85b5[{"name":"textures","value":"ewogICJ0aW1lc3RhbXAiIDogMTY1OTYyNjMzNDI3MiwKICAicHJvZmlsZUlkIiA6ICIyOGU4NzFiNjM0M2U0MDI0YjcxMDdjNTE5MWZmODViNSIsCiAgInByb2ZpbGVOYW1lIiA6ICJGb3VkcmVtYWdpYyIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83NDVkNzU3Mjg2MTdiODY2MjdkNTVjNTJkNDkxOGRlMDk3MDkxYzMzMzI0MGVmZWIyZWM0Yzg5MWZjMjgyNDYyIgogICAgfSwKICAgICJDQVBFIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yMzQwYzBlMDNkZDI0YTExYjE1YThiMzNjMmE3ZTllMzJhYmIyMDUxYjI0ODFkMGJhN2RlZmQ2MzVjYTdhOTMzIgogICAgfQogIH0KfQ\u003d\u003d","signature":"RlDoNCZ/Ic3iNVxVZSgbWvdj0r7xiK4114qcowRY5S4eMLCcXJZmViilOc/SsnpMnmqr/lLa63h+EhVdmbH22D0rzK0sYiarbCLraZEExcEouLrzLEJgmjst6UQLBnkAQB8Zjfy38JSqUQdm/VZhsN3fDZ1l+3TW6X+NUrqkr/CCJeeMzttGZ+/KUhbRSSfs6lr2ZIefQpmyLPenles/r2RsDZQJbNwZDHXOUpJHrFx7U2F6LMprZEx/s+1mvN/TkUz+G8T+ft7WyqplBdziqugJ28SwU/47sei5xfwMz/NyUsQPwjCNdl8AhqOA3pWjLcDfXwoOHZIHwiJfEoNyT8EgUBPu+BcimW3PICXjrhnPnEA0YF4iPfPvnpWKDIGK8ekt7pZRNthEzTl4oRBt/rcXIj6IcG2dB4QWqOP5rLG99yfHr9Bq4D9PD69joXZWlz89OHyoLj+stwCOJcYRiuNtTE7rDWu4CcRQAr7oI0jdZLqgIJ4QIBsdUrPlneohm5S2F/cVsATZd2BVSMOYhijKOrHdxRqQLC5tAE9rp6boPN2dn+JQn89GcfEbegLw9s6cp7Na7yTUZnfmRrQRBkDPAieIRlpsNPNBQU1b3y4+dLncyFvMHETvtUV6CZGRe4JdtIYSIsDy/8D7qincMGXkEjQT2f0yH+zR9OoVBmc\u003d"}]
    port=63380
    d=LOGIN
  ]
[16:18:54 INFO]: UUID of player Foudremagic is 28e871b6-343e-4024-b710-7c5191ff85b5
[16:18:54 INFO]: Foudremagic[/*************] logged in with entity id 326 at ([world]479.1394923008942, 72.3890328518999, 117.85322914760584)
[16:18:54 INFO]: Foudremagic lost connection: Disconnected
[16:18:54 INFO]: Foudremagic left the game

I've didn't touched the config of any plugins and a few days ago the network was perfectly working with no issues 

Awaiting your respond !

Foudremagic.

**Comment by PoudreMODInc** [comment]
ps: the token is the same from proxy to server01

**Comment by PoudreMODInc** [comment]
well I fixed it myself sorry for the false issue
