### ISSUE TITLE
Error while loading

### ISSUE THREAD

**Issue by WaterChick** [lucko/BungeeGuard#95]
Spigot 1.8.8

[ERROR] Error occurred while enabling BungeeGuard v1.3-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Server$Spigot.getSpigotConfig()Lorg/bukkit/configuration/file/YamlConfiguration;
at me.lucko.bungeeguard.spigot.BungeeGuardBackendPlugin.onEnable(BungeeGuardBackendPlugin.java:57) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-Spigot-21fe707-741a1bd]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server.jar:git-Spigot-21fe707-741a1bd]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-21fe707-741a1bd]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [server.jar:git-Spigot-21fe707-741a1bd]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [server.jar:git-Spigot-21fe707-741a1bd]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [server.jar:git-Spigot-21fe707-741a1bd]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [server.jar:git-Spigot-21fe707-741a1bd]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

**Comment by stijnb1234** [comment]
BungeeGuard only supports 1.9.4 or higher, as stated in the INSTALLATION.md document.

**Comment by WaterChick** [comment]
And what do i do with this information ?

**Comment by stijnb1234** [comment]
Nothing, that's for @lucko.

**Comment by WaterChick** [comment]
Okay.

**Comment by WaterChick** [comment]
When will it be fixed ?

**Comment by stijnb1234** [comment]
When someone looks at it. Look at the open issues before this one. 😉

**Comment by stijnb1234** [comment]
You can try an older version. This was bug was introduced in the latest commit.

**Comment by WaterChick** [comment]
Ur right. Thank you.

**Comment by Minecon724** [comment]
same issue on spigot 1.19.3

**Comment by stijnb1234** [comment]
Try PaperSpigot instead of Spigot.
