### ISSUE TITLE
Incompatibility with EaglercraftXBungee

### ISSUE THREAD

**Issue by vhcrack** [lucko/BungeeGuard#97]
Was told to post this here by someone in an Eaglercraft discord. My theory is that it isn't carrying the token when the handshake happens. Is there a way this could be possibly fixed?

```
[12:23:02 INFO]: UUID of player vhcrackier is aac5e64d-86a8-3a3e-bedb-7f691b1cbc68
[12:23:02 INFO]: vhcrackier[/212.192.28.148:44604] logged in with entity id 569192 at ([world]-75.48200412499142, 42.0, -133.46735466393102)
[12:23:02 INFO]: vhcrackier lost connection: Disconnected
[12:28:15 WARN]: [BungeeGuard] Denying connection from 172.18.0.1 - aac5e64d-86a8-3a3e-bedb-7f691b1cbc68 @ MjEyLjE5Mi4yOC4xNDg= - reason: NO_TOKEN
[12:28:15 ERROR]: [BungeeGuard] Unhandled exception occured in onPacketReceiving(PacketEvent) for BungeeGuard
java.lang.NoClassDefFoundError: com/comphenix/protocol/injector/temporary/TemporaryPlayerFactory
        at me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener.closeConnection(ProtocolHandshakeListener.java:134) ~[BungeeGuard.jar:?]
        at me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener.access$300(ProtocolHandshakeListener.java:55) ~[BungeeGuard.jar:?]
        at me.lucko.bungeeguard.spigot.listener.ProtocolHandshakeListener$Adapter.onPacketReceiving(ProtocolHandshakeListener.java:104) ~[BungeeGuard.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.8.0]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.8.0]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) [ProtocolLib.jar:4.8.0]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) [ProtocolLib.jar:4.8.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) [ProtocolLib.jar:4.8.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) [ProtocolLib.jar:4.8.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:600) [ProtocolLib.jar:4.8.0]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292) [ProtocolLib.jar:4.8.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.LegacyPingHandler.channelRead(SourceFile:94) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_342]
[12:28:15 ERROR]: Parameters: 
  net.minecraft.server.v1_8_R3.PacketHandshakingInSetProtocol@2d8a8cfc[
    a=47
    hostname=lopobia.sparked.miami212.192.28.148aac5e64d86a83a3ebedb7f691b1cbc68[{"name":"isEaglerPlayer","value":"true"}]
    port=25565
    d=LOGIN
  ]
```

**Comment by vhcrack** [comment]
This might be an invalid issue.

**Comment by heys1234** [comment]
[12:28:15 WARN]: [BungeeGuard] Denying connection from 172.18.0.1 - aac5e64d-86a8-3a3e-bedb-7f691b1cbc68 @ MjEyLjE5Mi4yOC4xNDg= - reason: NO_TOKEN

**Comment by heys1234** [comment]
might be why

**Comment by vhcrack** [comment]
> might be why

Yeah, it seems to be an issue on EaglercraftXBungee's end. I will have to wait for an eventual fix, I have other ways of  letting players connect for now.

**Comment by vhcrack** [comment]
> Duplicate of #92, only 1.9.4 and higher is supported by BungeeGuard.

Aw man. Thanks for the info, will close this now!

**Comment by vhcrack** [comment]
> Duplicate of #92, only 1.9.4 and higher is supported by BungeeGuard.

Reopening this. Wasn't 1.8 support for BungeeGuard added in #33? Also my base servers aren't in 1.8, I'm using ViaVersion. I use a standalone limbo server too at [NanoLimbo](https://www.spigotmc.org/resources/nanolimbo-1-7-1-19.86198/)

**Comment by vhcrack** [comment]
> That's why I said, 'duplicate of'. In the current state it only supports 1.9.4 or higher because the 1.8 support is not fully working.

Alright.
