### ISSUE TITLE
Error when someone try to join (with valid token)

### ISSUE THREAD

**Issue by KikyoC** [lucko/BungeeGuard#99]
Hii,
I got this:
19:39:40 [WARNING] [Aegis] {0} - Exception caught! {1} (To see details enable print-stacktraces)
19:39:43 [WARNING] Error dispatching event LoginEvent(cancelled=false, cancelReasonComponents=null, connection=[Kikyo_c,/88.165.25.94:35995] <-> InitialHandler) to listener me.lucko.bungeeguard.bungee.BungeeGuardProxyPlugin@5fbae40
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at me.lucko.bungeeguard.bungee.SpoofedLoginResult.inject(SpoofedLoginResult.java:87)
    at me.lucko.bungeeguard.bungee.BungeeGuardProxyPlugin.onLogin(BungeeGuardProxyPlugin.java:111)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:29)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:402)
    at net.md_5.bungee.connection.InitialHandler.finishLogin(InitialHandler.java:899)
    at xyz.yooniks.aegis.auth.handler.AuthConnector.completeLogin(AuthConnector.java:440)
    at xyz.yooniks.aegis.auth.thread.AegisAuthThread.lambda$start$0(AegisAuthThread.java:67)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
    at me.lucko.bungeeguard.bungee.SpoofedLoginResult.inject(SpoofedLoginResult.java:84)
    ... 12 more
Caused by: java.lang.NoSuchMethodError: 'net.md_5.bungee.protocol.Property[] net.md_5.bungee.connection.LoginResult.getProperties()'
    at me.lucko.bungeeguard.bungee.SpoofedLoginResult.<init>(SpoofedLoginResult.java:112)
    at me.lucko.bungeeguard.bungee.SpoofedLoginResultJava9.<init>(SpoofedLoginResultJava9.java:36)
    ... 18 more

bungee: aegis
spigot: imanity

This is officials and lasted versions of bungeeguard, aegis, and imanity

Thank to read me and have a nice day ^^
Kikyo

**Comment by stijnb1234** [comment]
Aegis should already contain protection. It's broken by missing classes in Aegis.

**Comment by stijnb1234** [comment]
And duplicate of #95
